name: Sync

on:
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Fetch Firebase JSON
        run: |
          curl -s https://my-book-project-c5a17-default-rtdb.asia-southeast1.firebasedatabase.app/movies.json -o data.json

      - name: Commit & Push (overwrite always)
        run: |
          git add data.json
          git commit -m "Update data.json from Firebase (overwrite)" || echo "No changes to commit"
          git pull --rebase origin main || git rebase --abort
          git push origin main
