name: Auto Sync Firebase JSON

on:
  schedule:
    - cron: "*/5 * * * *"   # প্রতি 5 মিনিটে রান হবে
  workflow_dispatch:        # চাইলে ম্যানুয়ালি রান করতে পারো

jobs:
  update-json:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Fetch JSON from Firebase
        run: |
          curl -s "https://talha-07-live.github.io/firebase-sync-data/data.json" -o data.json

      - name: Commit and Push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add data.json
          git commit -m "Auto update data.json from Firebase [skip ci]" || echo "No changes to commit"
          git push
