name: Firebase Sync

on:
  schedule:
    - cron: "*/5 * * * *"  # প্রতি 10 মিনিটে auto sync
  workflow_dispatch:        # optionally manual run

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Firebase
        run: npm install firebase-admin

      - name: Sync Firebase to data.json
        run: node sync.js
        env:
          FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
